In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import cluster, neighbors, svm, metrics, preprocessing

In [2]:
df = pd.read_csv('BankChurners.csv', delimiter=",")

In [3]:
import warnings
import numpy as np
warnings.simplefilter(action='ignore', category=FutureWarning)
print('x' in np.arange(5))   #returns False, without Warning

False


In [4]:
for column in df.columns:
    df = df[df[column] != "Unknown"]

In [5]:
df = df.drop(columns=['CLIENTNUM','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'])

In [6]:
df

Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      Existing Customer            45      M                3   
1      Existing Customer            49      F                5   
2      Existing Customer            51      M                3   
4      Existing Customer            40      M                3   
5      Existing Customer            44      M                2   
...                  ...           ...    ...              ...   
10120  Existing Customer            54      M                1   
10121  Existing Customer            56      F                1   
10122  Existing Customer            50      M                2   
10124  Attrited Customer            44      F                1   
10126  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
5            Graduate        Married     $40K - $60K          Blue   
...               ...            ...             ...           ...   
10120     High School         Single     $60K - $80K          Blue   
10121        Graduate         Single  Less than $40K          Blue   
10122        Graduate         Single     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0                  39                         5                       1   
1                  44                         6                       1   
2                  36                         4                       1   
4                  21                         5                       1   
5                  36                         3                       1   
...               ...                       ...                     ...   
10120              34                         5                       2   
10121              50                         4                       1   
10122              40                         3                       2   
10124              36                         5                       3   
10126              25                         6                       2   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                          3       12691.0                  777   
1                          2        8256.0                  864   
2                          0        3418.0                    0   
4                          0        4716.0                    0   
5                          2        4010.0                 1247   
...                      ...           ...                  ...   
10120                      0       13940.0                 2109   
10121                      4        3688.0                  606   
10122                      3        4003.0                 1851   
10124                      4        5409.0                    0   
10126                      4       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
4               4716.0                 2.175              816              28   
5               2763.0                 1.376             1088              24   
...                ...                   ...              ...             ...   
10120          11831.0                 0.660            15577             114   
10121           3082.0

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [8]:
le = LabelEncoder()
count = 0
for col in df.columns[1:]:
    if df[col].dtype == 'object':
        if len(list(df[col].unique())) <= 2:
            le.fit(df[col])
            df[col] = le.transform(df[col])

In [9]:
df

Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0      Existing Customer            45       1                3   
1      Existing Customer            49       0                5   
2      Existing Customer            51       1                3   
4      Existing Customer            40       1                3   
5      Existing Customer            44       1                2   
...                  ...           ...     ...              ...   
10120  Existing Customer            54       1                1   
10121  Existing Customer            56       0                1   
10122  Existing Customer            50       1                2   
10124  Attrited Customer            44       0                1   
10126  Attrited Customer            43       0                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
5            Graduate        Married     $40K - $60K          Blue   
...               ...            ...             ...           ...   
10120     High School         Single     $60K - $80K          Blue   
10121        Graduate         Single  Less than $40K          Blue   
10122        Graduate         Single     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0                  39                         5                       1   
1                  44                         6                       1   
2                  36                         4                       1   
4                  21                         5                       1   
5                  36                         3                       1   
...               ...                       ...                     ...   
10120              34                         5                       2   
10121              50                         4                       1   
10122              40                         3                       2   
10124              36                         5                       3   
10126              25                         6                       2   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                          3       12691.0                  777   
1                          2        8256.0                  864   
2                          0        3418.0                    0   
4                          0        4716.0                    0   
5                          2        4010.0                 1247   
...                      ...           ...                  ...   
10120                      0       13940.0                 2109   
10121                      4        3688.0                  606   
10122                      3        4003.0                 1851   
10124                      4        5409.0                    0   
10126                      4       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
4               4716.0                 2.175              816              28   
5               2763.0                 1.376             1088              24   
...                ...                   ...              ...             ...   
10120          11831.0                 0.660            15577             114   
10121     

In [10]:
le = preprocessing.LabelEncoder() #transforma atributos qualitativos em quantitativos
for column in df.columns:
    if df[column].dtypes == 'object':
        df[column] = le.fit_transform(df[column])

In [11]:
df

Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0                   1            45       1                3                3   
1                   1            49       0                5                2   
2                   1            51       1                3                2   
4                   1            40       1                3                5   
5                   1            44       1                2                2   
...               ...           ...     ...              ...              ...   
10120               1            54       1                1                3   
10121               1            56       0                1                2   
10122               1            50       1                2                2   
10124               0            44       0                1                3   
10126               0            43       0                2                2   

       Marital_Status  Income_Category  Card_Category  Months_on_book  \
0                   1                2              0              39   
1                   2                4              0              44   
2                   1                3              0              36   
4                   1                2              0              21   
5                   1                1              0              36   
...               ...              ...            ...             ...   
10120               2                2              0              34   
10121               2                4              0              50   
10122               2                1              0              40   
10124               1                4              0              36   
10126               1                4              3              25   

       Total_Relationship_Count  Months_Inactive_12_mon  \
0                             5                       1   
1                             6                       1   
2                             4                       1   
4                             5                       1   
5                             3                       1   
...                         ...                     ...   
10120                         5                       2   
10121                         4                       1   
10122                         3                       2   
10124                         5                       3   
10126                         6                       2   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                          3       12691.0                  777   
1                          2        8256.0                  864   
2                          0        3418.0                    0   
4                          0        4716.0                    0   
5                          2        4010.0                 1247   
...                      ...           ...                  ...   
10120                      0       13940.0                 2109   
10121                      4        3688.0                  606   
10122                      3        4003.0                 1851   
10124                      4        5409.0                    0   
10126                      4       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
4               4716.0                 2.175              816              28   
5               2763.0                 1.376             1088              24   
...                ...                   ...              ...             ...   
10120          11831.0                 0.660            15577             11

In [12]:
from sklearn import preprocessing
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA

In [13]:
scaler = preprocessing.MinMaxScaler()
names = df.columns
d = scaler.fit_transform(df)
df_normal = pd.DataFrame(d, columns=names)

In [14]:
df_normal

Attrition_Flag  Customer_Age  Gender  Dependent_count  Education_Level  \
0                1.0      0.404255     1.0              0.6              0.6   
1                1.0      0.489362     0.0              1.0              0.4   
2                1.0      0.531915     1.0              0.6              0.4   
3                1.0      0.297872     1.0              0.6              1.0   
4                1.0      0.382979     1.0              0.4              0.4   
...              ...           ...     ...              ...              ...   
7076             1.0      0.595745     1.0              0.2              0.6   
7077             1.0      0.638298     0.0              0.2              0.4   
7078             1.0      0.510638     1.0              0.4              0.4   
7079             0.0      0.382979     0.0              0.2              0.6   
7080             0.0      0.361702     0.0              0.4              0.4   

      Marital_Status  Income_Category  Card_Category  Months_on_book  \
0                0.5             0.50            0.0        0.604651   
1                1.0             1.00            0.0        0.720930   
2                0.5             0.75            0.0        0.534884   
3                0.5             0.50            0.0        0.186047   
4                0.5             0.25            0.0        0.534884   
...              ...              ...            ...             ...   
7076             1.0             0.50            0.0        0.488372   
7077             1.0             1.00            0.0        0.860465   
7078             1.0             0.25            0.0        0.627907   
7079             0.5             1.00            0.0        0.534884   
7080             0.5             1.00            1.0        0.279070   

      Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                          0.8                0.166667               0.500000   
1                          1.0                0.166667               0.333333   
2                          0.6                0.166667               0.000000   
3                          0.8                0.166667               0.000000   
4                          0.4                0.166667               0.333333   
...                        ...                     ...                    ...   
7076                       0.8                0.333333               0.000000   
7077                       0.6                0.166667               0.666667   
7078                       0.4                0.333333               0.500000   
7079                       0.8                0.500000               0.666667   
7080                       1.0                0.333333               0.666667   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
0         0.340190             0.308701         0.345116   
1         0.206112             0.343266         0.214093   
2         0.059850             0.000000         0.098948   
3         0.099091             0.000000         0.136557   
4         0.077747             0.495431         0.079970   
...            ...                  ...              ...   
7076      0.377949             0.837902         0.342711   
7077      0.068013             0.240763         0.089213   
7078      0.077536             0.735399         0.062266   
7079      0.120042             0.000000         0.156637   
7080      0.270566             0.779102         0.244082   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0                 0.392994         0.036260        0.258065   
1                 0.453636         0.044667        0.185484   
2                 0.763615         0.078753        0.080645   
3                 0.640271         0.017501        0.145161   
4                 0.405063         0.033057        0.112903   
...                    ...              ...             ...   
7076              0.194289         0.861710  

In [15]:
trainSample = df.sample(frac=0.8, random_state = 1) #seleção de 80% da base para treinamento
testSample = pd.concat([df, trainSample]).drop_duplicates(keep=False) #concatena a base original com a base de treinamento e exclui os duplicados, sobrando a amostra de teste

trainTarget = trainSample["Attrition_Flag"] #define o atributo alvo da base para o treinamento
testTarget = testSample["Attrition_Flag"] #define o atributo alvo da base para o teste


del testSample["Attrition_Flag"]
del trainSample["Attrition_Flag"]

In [16]:
knn = neighbors.KNeighborsClassifier(n_neighbors=1, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [17]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 132   98]
 [  62 1124]]


In [18]:
testSample

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
2                51       1                3                2               1   
25               41       0                3                2               2   
29               47       1                4                3               1   
33               53       0                2                0               1   
35               55       0                1                0               2   
...             ...     ...              ...              ...             ...   
10093            38       1                1                3               2   
10099            51       0                1                2               2   
10105            59       0                1                3               1   
10111            49       1                1                2               2   
10114            29       1                0                2               1   

       Income_Category  Card_Category  Months_on_book  \
2                    3              0              36   
25                   4              0              28   
29                   1              0              42   
33                   4              0              38   
35                   4              0              36   
...                ...            ...             ...   
10093                2              0              28   
10099                4              0              41   
10105                4              0              50   
10111                2              0              40   
10114                4              0              15   

       Total_Relationship_Count  Months_Inactive_12_mon  \
2                             4                       1   
25                            6                       1   
29                            6                       0   
33                            5                       2   
35                            4                       2   
...                         ...                     ...   
10093                         2                       2   
10099                         4                       2   
10105                         1                       4   
10111                         6                       3   
10114                         3                       1   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
2                          0        3418.0                    0   
25                         2        7768.0                 1669   
29                         0        4785.0                 1362   
33                         3        2650.0                 1490   
35                         1        3520.0                 1914   
...                      ...           ...                  ...   
10093                      2       21906.0                    0   
10099                      3        8900.0                  798   
10105                      3        5043.0                  743   
10111                      3        6481.0                 1569   
10114                      5        4700.0                    0   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
2               3418.0                 2.594             1887              20   
25              6099.0                 0.797             1051              22   
29              3423.0                 0.739             1045              38   
33              1160.0                 1.750             1411              28   
35              1606.0                 0.510             1407              43   
...                ...                   ...              ...             ...   
10093          21906.0                 0.696            15349             119   
10099           8102.0                 0.647            16737              88   
10105           4300.0                 0.805            10170              66   
10111           4912.0   

In [19]:
trainSample

Customer_Age  Gender  Dependent_count  Education_Level  Marital_Status  \
424             44       0                4                0               1   
9955            48       1                3                5               0   
9795            46       1                2                3               1   
9194            51       0                3                5               1   
4017            45       1                3                5               1   
...            ...     ...              ...              ...             ...   
8863            43       1                3                4               1   
3902            50       1                3                5               2   
1635            46       1                2                3               1   
8678            38       0                3                2               2   
8189            54       0                1                3               2   

      Income_Category  Card_Category  Months_on_book  \
424                 4              3              37   
9955                1              0              35   
9795                2              1              38   
9194                4              0              46   
4017                4              0              39   
...               ...            ...             ...   
8863                1              2              31   
3902                0              0              36   
1635                2              0              35   
8678                4              1              31   
8189                4              0              36   

      Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
424                          3                       2                      2   
9955                         3                       5                      3   
9795                         5                       3                      6   
9194                         5                       5                      2   
4017                         3                       3                      4   
...                        ...                     ...                    ...   
8863                         2                       3                      4   
3902                         5                       3                      4   
1635                         6                       3                      3   
8678                         2                       3                      2   
8189                         1                       3                      2   

      Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  \
424        10790.0                 1930           8860.0   
9955       11427.0                 2307           9120.0   
9795       34516.0                 2517          31999.0   
9194        3536.0                    0           3536.0   
4017        8580.0                 1636           6944.0   
...            ...                  ...              ...   
8863       23981.0                  593          23388.0   
3902       27876.0                  557          27319.0   
1635       13768.0                  763          13005.0   
8678       15987.0                 1766          14221.0   
8189        1572.0                  985            587.0   

      Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
424                  0.750             1052              16   
9955                 0.848            15243             107   
9795                 0.956             9314              89   
9194                 0.542             3281              39   
4017                 0.393             1880              37   
...                    ...              ...             ...   
8863                 0.987             4758              65   
3902                 0.768             4654              88   
1635                 0.712             1390              44   
8678                 0.791             8195     

In [20]:
knn = neighbors.KNeighborsClassifier(n_neighbors=15, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [21]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 109  121]
 [  41 1145]]


In [22]:
knn = neighbors.KNeighborsClassifier(n_neighbors=30, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [23]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.88
Matriz de Confusão:
 [[ 103  127]
 [  38 1148]]


In [24]:
knn = neighbors.KNeighborsClassifier(n_neighbors=1, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [25]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 132   98]
 [  62 1124]]


In [26]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.92


In [27]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.11


In [28]:
knn = neighbors.KNeighborsClassifier(n_neighbors=15, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [29]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 109  121]
 [  41 1145]]


In [30]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.90


In [31]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.11


In [32]:
knn = neighbors.KNeighborsClassifier(n_neighbors=31, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [33]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.88
Matriz de Confusão:
 [[  98  132]
 [  36 1150]]


In [34]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.90


In [35]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.12


In [36]:
knn = neighbors.KNeighborsClassifier(n_neighbors=2, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [37]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.87
Matriz de Confusão:
 [[ 168   62]
 [ 122 1064]]


In [38]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.93


In [39]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.13


In [40]:
knn = neighbors.KNeighborsClassifier(n_neighbors=5, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [41]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 128  102]
 [  48 1138]]


In [42]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.91


In [43]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.11


<h2> Mudando Métrica

In [45]:
knn = neighbors.KNeighborsClassifier(n_neighbors=1, algorithm="auto", metric="manhattan") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [46]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 137   93]
 [  65 1121]]


In [47]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.92


In [48]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.11


In [49]:
knn = neighbors.KNeighborsClassifier(n_neighbors=1, algorithm="auto", metric="chebyshev") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [50]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 137   93]
 [  62 1124]]


In [51]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.92


In [52]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.11


In [53]:
knn = neighbors.KNeighborsClassifier(n_neighbors=1, algorithm="auto", metric="euclidean") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [54]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 132   98]
 [  62 1124]]


In [55]:
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))

Precisão Média: 0.92


In [56]:
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

Brier Score Loss: 0.11
