In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import cluster, neighbors, svm, metrics, preprocessing

In [2]:
df = pd.read_csv('BankChurners.csv', delimiter=",")

In [3]:
for column in df.columns:
    df = df[df[column] != "Unknown"]

/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/

In [4]:
df = df.drop(columns=['Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'])

In [5]:
le = preprocessing.LabelEncoder() #transforma atributos qualitativos em quantitativos
for column in df.columns:
    if df[column].dtypes == 'object':
        df[column] = le.fit_transform(df[column])
        
print(df)

       CLIENTNUM  Attrition_Flag  Customer_Age  Gender  Dependent_count  \
0      768805383               1            45       1                3   
1      818770008               1            49       0                5   
2      713982108               1            51       1                3   
4      709106358               1            40       1                3   
5      713061558               1            44       1                2   
...          ...             ...           ...     ...              ...   
10120  710841183               1            54       1                1   
10121  713899383               1            56       0                1   
10122  772366833               1            50       1                2   
10124  716506083               0            44       0                1   
10126  714337233               0            43       0                2   

       Education_Level  Marital_Status  Income_Category  Card_Category  \
0                    3   

In [6]:
trainSample = df.sample(frac=0.8, random_state = 1) #seleção de 80% da base para treinamento
testSample = pd.concat([df, trainSample]).drop_duplicates(keep=False) #concatena a base original com a base de treinamento e exclui os duplicados, sobrando a amostra de teste

trainTarget = trainSample["Income_Category"] #define o atributo alvo da base para o treinamento
testTarget = testSample["Income_Category"] #define o atributo alvo da base para o teste


del testSample["Income_Category"]
del trainSample["Income_Category"]

In [7]:
knn = neighbors.KNeighborsClassifier(n_neighbors=1, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [8]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.31
Matriz de Confusão:
 [[ 14  17  22  24  30]
 [ 12  63  35  30 150]
 [ 21  61  33  40  71]
 [ 18  39  43  57  63]
 [ 19 154  65  61 274]]


In [9]:
knn = neighbors.KNeighborsClassifier(n_neighbors=5, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [10]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.33
Matriz de Confusão:
 [[ 10  19  17  23  38]
 [ 14  80  27  18 151]
 [ 20  54  35  31  86]
 [ 17  50  35  32  86]
 [ 16 165  36  47 309]]


In [11]:
trainSample = df.sample(frac=0.8, random_state = 1) #seleção de 80% da base para treinamento
testSample = pd.concat([df, trainSample]).drop_duplicates(keep=False) #concatena a base original com a base de treinamento e exclui os duplicados, sobrando a amostra de teste

trainTarget = trainSample["Avg_Utilization_Ratio"] #define o atributo alvo da base para o treinamento
testTarget = testSample["Avg_Utilization_Ratio"] #define o atributo alvo da base para o teste


del testSample["Avg_Utilization_Ratio"]
del trainSample["Avg_Utilization_Ratio"]

In [12]:
knn = neighbors.KNeighborsRegressor(n_neighbors=5, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


In [13]:
resultKNN


array([0.4456, 0.2344, 0.3442, ..., 0.3732, 0.4344, 0.345 ])

In [14]:
print("\nK-NN")
print("Erro maximo: %0.2f" % (metrics.max_error(testTarget, resultKNN)))


K-NN
Erro maximo: 0.83


In [15]:
print("\nK-NN")
print("Media Erro absoluto: %0.2f" % (metrics.mean_absolute_error(testTarget, resultKNN)))


K-NN
Media Erro absoluto: 0.24


In [16]:
trainSample = df.sample(frac=0.8, random_state = 1) #seleção de 80% da base para treinamento
testSample = pd.concat([df, trainSample]).drop_duplicates(keep=False) #concatena a base original com a base de treinamento e exclui os duplicados, sobrando a amostra de teste

trainTarget = trainSample["Income_Category"] #define o atributo alvo da base para o treinamento
testTarget = testSample["Income_Category"] #define o atributo alvo da base para o teste


del testSample["Income_Category"]
del trainSample["Income_Category"]

In [17]:
knn = neighbors.KNeighborsClassifier(n_neighbors=15, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [18]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.36
Matriz de Confusão:
 [[  3  19   8  12  65]
 [  0  55  15  13 207]
 [  3  37  16  13 157]
 [  0  33  15  25 147]
 [  0 106  24  27 416]]


In [19]:
knn = neighbors.KNeighborsClassifier(n_neighbors=100, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [20]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.41
Matriz de Confusão:
 [[  0   0   0   0 107]
 [  0   2   0   0 288]
 [  0   0   0   0 226]
 [  0   1   0   1 218]
 [  0   0   0   0 573]]


In [21]:
knn = neighbors.KNeighborsClassifier(n_neighbors=700, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [22]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.40
Matriz de Confusão:
 [[  0   0   0   0 107]
 [  0   0   0   0 290]
 [  0   0   0   0 226]
 [  0   0   0   0 220]
 [  0   0   0   0 573]]


In [23]:
knn = neighbors.KNeighborsClassifier(n_neighbors=100, weights="distance", algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample, trainTarget)
resultKNN = knn.predict(testSample)

/home/rafael/.local/lib/python3.8/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [24]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.38
Matriz de Confusão:
 [[  1   7   4   8  87]
 [  1  27  11   5 246]
 [  1  18   9   8 190]
 [  1  13   8   6 192]
 [  1  51  15  16 490]]


In [25]:
testTarget

2        3
25       4
29       1
33       4
35       4
        ..
10093    2
10099    4
10105    4
10111    2
10114    4
Name: Income_Category, Length: 1416, dtype: int64

In [29]:
type(testTarget)

pandas.core.series.Series

In [30]:
testTarget.index

Int64Index([    2,    25,    29,    33,    35,    48,    51,    66,    67,
               70,
            ...
            10075, 10080, 10085, 10086, 10087, 10093, 10099, 10105, 10111,
            10114],
           dtype='int64', length=1416)

In [31]:
testTarget[2]

3

In [32]:
resultKNN[2]

4

In [33]:
resultKNN

array([4, 4, 4, ..., 4, 4, 4])

In [34]:
print(resultKNN)

[4 4 4 ... 4 4 4]


In [35]:
resultKNN[764]

4

In [38]:
for i in resultKNN:
    if(i != 4):
        print(i)

0
3
1
1
3
1
3
0
2
1
3
1
2
2
3
3
1
3
2
2
2
1
1
3
3
1
3
1
3
1
1
1
2
3
1
1
1
1
3
1
2
1
1
1
2
1
1
2
3
1
1
1
2
1
2
3
1
1
1
1
1
2
1
1
2
1
1
1
3
1
2
1
3
1
3
2
1
2
3
1
1
3
3
3
1
2
2
2
2
1
3
1
1
3
1
1
2
1
1
2
1
1
3
3
1
2
2
2
1
1
1
1
1
2
2
1
3
1
1
2
2
2
1
2
3
1
0
2
2
0
1
3
2
1
3
1
1
3
1
1
3
3
1
1
3
1
1
1
2
1
1
1
1
3
3
3
1
3
1
1
2
1
1
2
1
2
1
1
3
1
1
1
1
0
2
1
1
1
1
1
2
1
3
2
1
3
1
1
1
1
1
2
3
1
1
1
1
1
3
1
1
2
2
1
1
2
1
1
2
1
1


In [39]:
df = pd.read_csv('BankChurners.csv', delimiter=",")

In [3]:
for column in df.columns:
    df = df[df[column] != "Unknown"]

/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/

In [41]:
df = df.drop(columns=['Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'])

KeyError: "['Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1'\n 'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'] not found in axis"

In [42]:
trainSample = df.sample(frac=0.8, random_state = 1) #seleção de 80% da base para treinamento
testSample = pd.concat([df, trainSample]).drop_duplicates(keep=False) #concatena a base original com a base de treinamento e exclui os duplicados, sobrando a amostra de teste

trainTarget = trainSample["Income_Category"] #define o atributo alvo da base para o treinamento
testTarget = testSample["Income_Category"] #define o atributo alvo da base para o teste


del testSample["Income_Category"]
del trainSample["Income_Category"]