In [1]:
import pandas as pd
import numpy as np
import statistics as st
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn import preprocessing
from sklearn.preprocessing import RobustScaler
from sklearn.decomposition import PCA
from sklearn import cluster, neighbors, svm, metrics, preprocessing

In [2]:
df = pd.read_csv('BankChurners.csv', delimiter=",")

In [3]:
for column in df.columns:
    df = df[df[column] != "Unknown"]

/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:68: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return op(a, b)
/home/rafael/.local/lib/python3.8/site-packages/pandas/core/

In [4]:
df = df.drop(columns=['CLIENTNUM','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1','Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'])

In [5]:
df

Attrition_Flag  Customer_Age Gender  Dependent_count  \
0      Existing Customer            45      M                3   
1      Existing Customer            49      F                5   
2      Existing Customer            51      M                3   
4      Existing Customer            40      M                3   
5      Existing Customer            44      M                2   
...                  ...           ...    ...              ...   
10120  Existing Customer            54      M                1   
10121  Existing Customer            56      F                1   
10122  Existing Customer            50      M                2   
10124  Attrited Customer            44      F                1   
10126  Attrited Customer            43      F                2   

      Education_Level Marital_Status Income_Category Card_Category  \
0         High School        Married     $60K - $80K          Blue   
1            Graduate         Single  Less than $40K          Blue   
2            Graduate        Married    $80K - $120K          Blue   
4          Uneducated        Married     $60K - $80K          Blue   
5            Graduate        Married     $40K - $60K          Blue   
...               ...            ...             ...           ...   
10120     High School         Single     $60K - $80K          Blue   
10121        Graduate         Single  Less than $40K          Blue   
10122        Graduate         Single     $40K - $60K          Blue   
10124     High School        Married  Less than $40K          Blue   
10126        Graduate        Married  Less than $40K        Silver   

       Months_on_book  Total_Relationship_Count  Months_Inactive_12_mon  \
0                  39                         5                       1   
1                  44                         6                       1   
2                  36                         4                       1   
4                  21                         5                       1   
5                  36                         3                       1   
...               ...                       ...                     ...   
10120              34                         5                       2   
10121              50                         4                       1   
10122              40                         3                       2   
10124              36                         5                       3   
10126              25                         6                       2   

       Contacts_Count_12_mon  Credit_Limit  Total_Revolving_Bal  \
0                          3       12691.0                  777   
1                          2        8256.0                  864   
2                          0        3418.0                    0   
4                          0        4716.0                    0   
5                          2        4010.0                 1247   
...                      ...           ...                  ...   
10120                      0       13940.0                 2109   
10121                      4        3688.0                  606   
10122                      3        4003.0                 1851   
10124                      4        5409.0                    0   
10126                      4       10388.0                 1961   

       Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  Total_Trans_Amt  Total_Trans_Ct  \
0              11914.0                 1.335             1144              42   
1               7392.0                 1.541             1291              33   
2               3418.0                 2.594             1887              20   
4               4716.0                 2.175              816              28   
5               2763.0                 1.376             1088              24   
...                ...                   ...              ...             ...   
10120          11831.0                 0.660            15577             114   
10121           3082.0

In [6]:
le = preprocessing.LabelEncoder() #transforma atributos qualitativos em quantitativos
for column in df.columns:
    if df[column].dtypes == 'object':
        df[column] = le.fit_transform(df[column])

In [7]:
scaler = preprocessing.MinMaxScaler()
names = df.columns
d = scaler.fit_transform(df)
df_normal = pd.DataFrame(d, columns=names)

In [8]:
df_pca = df_normal.drop(columns=['Attrition_Flag'])

In [9]:
pca = PCA(n_components = 10, copy = True) #executando o PCA
X = pca.fit_transform(df_pca)

In [10]:
X

array([[ 0.5467871 , -0.0229312 , -0.39591329, ..., -0.10928026,
        -0.11986367, -0.00440822],
       [-0.48868447,  0.34208152, -0.21417861, ..., -0.39696894,
        -0.39093586, -0.23841076],
       [ 0.31024591,  0.17282268, -0.57202704, ..., -0.1489579 ,
        -0.1832856 , -0.07817533],
       ...,
       [ 0.37507567, -0.41701176,  0.36374187, ...,  0.03546574,
         0.34776627, -0.43439241],
       [-0.48858782,  0.59452995, -0.27598617, ...,  0.17802083,
         0.33007849, -0.08637567],
       [-0.38447792,  0.19374862,  0.38439235, ..., -0.01825869,
         0.45431699,  0.08833232]])

In [11]:
df_pca = pd.DataFrame(X, columns = ["PC" + str(i) for i in range(0,10)])

In [12]:
df_pca

PC0       PC1       PC2       PC3       PC4       PC5       PC6  \
0     0.546787 -0.022931 -0.395913  0.181411  0.108532  0.075285 -0.018291   
1    -0.488684  0.342082 -0.214179  0.421324 -0.334433 -0.191440  0.145696   
2     0.310246  0.172823 -0.572027 -0.146570  0.204386 -0.092167 -0.287780   
3     0.417659  0.084293 -0.668358 -0.012212  0.128879  0.498377 -0.039433   
4     0.395354 -0.373839 -0.289612 -0.301063  0.196536 -0.090682  0.065405   
...        ...       ...       ...       ...       ...       ...       ...   
7076  0.529283 -0.239160  0.370609 -0.062724 -0.392908  0.068674 -0.105262   
7077 -0.559872  0.486273  0.208967 -0.189674 -0.298137 -0.072318 -0.144064   
7078  0.375076 -0.417012  0.363742 -0.610350 -0.254501 -0.072424  0.035271   
7079 -0.488588  0.594530 -0.275986  0.169078  0.121312  0.133472 -0.125923   
7080 -0.384478  0.193749  0.384392  0.813707  0.039161 -0.169907  0.062930   

           PC7       PC8       PC9  
0    -0.109280 -0.119864 -0.004408  
1    -0.396969 -0.390936 -0.238411  
2    -0.148958 -0.183286 -0.078175  
3    -0.370975  0.102955  0.114994  
4     0.070865 -0.121267  0.248332  
...        ...       ...       ...  
7076  0.110629  0.543723 -0.565443  
7077  0.312764  0.320969 -0.548030  
7078  0.035466  0.347766 -0.434392  
7079  0.178021  0.330078 -0.086376  
7080 -0.018259  0.454317  0.088332  

[7081 rows x 10 columns]

In [13]:
df_pca['Attrition_Flag'] = df_normal['Attrition_Flag']

In [14]:
df_pca

PC0       PC1       PC2       PC3       PC4       PC5       PC6  \
0     0.546787 -0.022931 -0.395913  0.181411  0.108532  0.075285 -0.018291   
1    -0.488684  0.342082 -0.214179  0.421324 -0.334433 -0.191440  0.145696   
2     0.310246  0.172823 -0.572027 -0.146570  0.204386 -0.092167 -0.287780   
3     0.417659  0.084293 -0.668358 -0.012212  0.128879  0.498377 -0.039433   
4     0.395354 -0.373839 -0.289612 -0.301063  0.196536 -0.090682  0.065405   
...        ...       ...       ...       ...       ...       ...       ...   
7076  0.529283 -0.239160  0.370609 -0.062724 -0.392908  0.068674 -0.105262   
7077 -0.559872  0.486273  0.208967 -0.189674 -0.298137 -0.072318 -0.144064   
7078  0.375076 -0.417012  0.363742 -0.610350 -0.254501 -0.072424  0.035271   
7079 -0.488588  0.594530 -0.275986  0.169078  0.121312  0.133472 -0.125923   
7080 -0.384478  0.193749  0.384392  0.813707  0.039161 -0.169907  0.062930   

           PC7       PC8       PC9  Attrition_Flag  
0    -0.109280 -0.119864 -0.004408             1.0  
1    -0.396969 -0.390936 -0.238411             1.0  
2    -0.148958 -0.183286 -0.078175             1.0  
3    -0.370975  0.102955  0.114994             1.0  
4     0.070865 -0.121267  0.248332             1.0  
...        ...       ...       ...             ...  
7076  0.110629  0.543723 -0.565443             1.0  
7077  0.312764  0.320969 -0.548030             1.0  
7078  0.035466  0.347766 -0.434392             1.0  
7079  0.178021  0.330078 -0.086376             0.0  
7080 -0.018259  0.454317  0.088332             0.0  

[7081 rows x 11 columns]

In [15]:
trainSample = df.sample(frac=0.8, random_state = 1) #seleção de 80% da base para treinamento
testSample = pd.concat([df, trainSample]).drop_duplicates(keep=False) #concatena a base original com a base de treinamento e exclui os duplicados, sobrando a amostra de teste

trainTarget = trainSample["Attrition_Flag"] #define o atributo alvo da base para o treinamento
testTarget = testSample["Attrition_Flag"] #define o atributo alvo da base para o teste


del testSample["Attrition_Flag"]
del trainSample["Attrition_Flag"]

In [16]:
knn = neighbors.KNeighborsClassifier(n_neighbors=3, algorithm="auto") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [17]:
print("\nK-NN")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))


matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)


K-NN
Acurácia: 0.89
Matriz de Confusão:
 [[ 127  103]
 [  54 1132]]


In [18]:
knn = neighbors.KNeighborsClassifier(n_neighbors=3, algorithm="auto", metric="manhattan") #k vizinhos mais próximos = n_neighbors
knn.fit(trainSample.values, trainTarget.values)
resultKNN = knn.predict(testSample.values)

In [19]:
print("N = 3 Manhattan")
print("Acurácia: %0.2f" % (metrics.accuracy_score(testTarget, resultKNN)))
print("Precisão Média: %0.2f" % (metrics.average_precision_score(testTarget, resultKNN)))
print("Brier Score Loss: %0.2f" % (metrics.brier_score_loss(testTarget, resultKNN)))

matrizConfusao = metrics.confusion_matrix(testTarget, resultKNN)
print("Matriz de Confusão:\n",matrizConfusao)

N = 3 Manhattan
Acurácia: 0.89
Precisão Média: 0.91
Brier Score Loss: 0.11
Matriz de Confusão:
 [[ 126  104]
 [  55 1131]]
